workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      - mkdir -p build/ios/ipa
      - cd build/ios/Release-iphoneos && mkdir -p Payload && cp -r Runner.app Payload/ && zip -r ../../../ios/ipa/Runner.ipa Payload/
    artifacts:
      - build/ios/ipa/*.ipa