workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      - mkdir -p /Users/builder/clone/build/ios/ipa/Payload
      - cp -r /Users/builder/clone/build/ios/Release-iphoneos/Runner.app /Users/builder/clone/build/ios/ipa/Payload/
      - cd /Users/builder/clone/build/ios/ipa && zip -r Runner.ipa Payload/
    artifacts:
      - build/ios/ipa/Runner.ipa