workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      - find $CM_BUILD_DIR/build -name "*.app" -type d
    artifacts:
      - build/ios/**/*.ipa